apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: ngrok
  name: ngrok
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ngrok
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: ngrok
    spec:
      containers:
        - env:
            - name: TARGET_HOST
              value: response
            - name: TARGET_PORT
              value: "8000"
          image: gtriggiano/ngrok-tunnel
          name: ngrok
          ports:
            - containerPort: 4040
          resources: {}
      restartPolicy: Always
status: {}
