apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: response
  name: response
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: response
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: response
    spec:
      containers:
        - args:
            - /app/startup.sh
          command:
            - bash
          env:
            - name: DJANGO_SETTINGS_MODULE
              valueFrom:
                configMapKeyRef:
                  key: DJANGO_SETTINGS_MODULE
                  name: env
            - name: INCIDENT_BOT_NAME
              valueFrom:
                configMapKeyRef:
                  key: INCIDENT_BOT_NAME
                  name: env
            - name: INCIDENT_CHANNEL_NAME
              valueFrom:
                configMapKeyRef:
                  key: INCIDENT_CHANNEL_NAME
                  name: env
            - name: POSTGRES
              value: "true"
            - name: SLACK_SIGNING_SECRET
              valueFrom:
                configMapKeyRef:
                  key: SLACK_SIGNING_SECRET
                  name: env
            - name: SLACK_TOKEN
              valueFrom:
                configMapKeyRef:
                  key: SLACK_TOKEN
                  name: env
          image: response:1
          imagePullPolicy: Never
          name: response
          ports:
            - containerPort: 8000
          resources: {}
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: /app
              name: response-claim0
            - mountPath: /response
              name: response-claim1
            - mountPath: /app/pypd
              name: pypd
      restartPolicy: Always
      volumes:
        - name: response-claim0
          persistentVolumeClaim:
            claimName: response-claim0
        - name: response-claim1
          persistentVolumeClaim:
            claimName: response-claim1
        - name: pypd
          persistentVolumeClaim:
            claimName: pypd
status: {}
