apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: {{ .Values.dispatch.appName }}
  name: {{ .Values.dispatch.appName }}
  namespace: {{ .Values.namespace}}
spec:
  ports:
    - name: "5555"
      port: 5555
      targetPort: 80
  selector:
    service: {{ .Values.dispatch.appName }}
status:
  loadBalancer: {}
