apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.postgres.appName }}
  name: {{ .Values.postgres.appName }}
  namespace: {{ .Values.namespace}}
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    service: {{ .Values.postgres.appName }}
status:
  loadBalancer: {}